import { createRoot } from 'react-dom/client'
import { useMemo, useState } from 'react'
import { ArrowRight, AtSign, Check, CreditCard, Globe2, Heart, Menu, Minus, PackageCheck, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, Truck, X } from 'lucide-react'
import './styles.css'

const company = { name: '笑爾貿易有限公司', email: 'xiaoerkejishop@outlook.com', address: 'RM 12, 3/F, BLK G, KWAI SHING IND BLDG (STAGE 2), 42-46 TAI LIN PAI RD, KWAI CHUNG, NT, HONG KONG' }
const categoryInfo = [
  { name: 'Furniture', key: 'furniture', label: 'Furniture', copy: 'Woodwork and seating for better everyday order', items: ['Sofa','Bed','Wardrobe','Dining table','Coffee table','Media console','Dresser','Sideboard','Bookcase','Desk'] },
  { name: 'Soft furnishings', key: 'soft', label: 'Textiles', copy: 'A softer layer for every room', items: ['Curtains','Rug','Cushion','Wall art','Faux plant','Sheer curtain','Wood blinds','Wallcloth','Tapestry','Bolster cushion'] },
  { name: 'Home essentials', key: 'daily', label: 'Daily living', copy: 'Useful comforts for every day', items: ['Bedding set','Storage box','Floor mat','Quilt','Pillow','Fitted sheet','Bath towel','Bathrobe','Laundry basket','Drawer box'] },
  { name: 'Decor & lighting', key: 'decor', label: 'Light & object', copy: 'The final layer of warm light and form', items: ['Scent diffuser','Table lamp','Floor lamp','Wall light','Decorative clock','Candle holder','Sculptural object','Faux floral','Lampshade','String light'] },
  { name: 'Kitchen & dining', key: 'kitchen', label: 'Kitchen', copy: 'Set the table for everyday rituals', items: ['Placemat','Tablecloth','Trivet','Kitchen rack','Wood tray','Spice rack','Lid organizer','Cutlery organizer','Food container','Sink caddy'] },
]
const names = { furniture:['Sculptural lounge chair','Portable folding bed','Slim shoe cabinet','Caramel dining chairs','Six-drawer storage cabinet','Narrow entry console','Walnut bedside table','Modular storage cabinet','Open bookcase','Quiet writing desk'], soft:['Linen blackout curtain','Low-pile rug','Color-block cushion','Linework wall art','Faux floral arrangement','Light sheer curtain','Wood blinds','Textured wallcloth','Handwoven tapestry','Linen bolster cushion'], daily:['Washed cotton bedding','Stackable storage box','Cork floor mat','Lightweight quilt','Cloud-support pillow','Cotton fitted sheet','Quick-dry bath towel','Waffle bathrobe','Woven laundry basket','Clear drawer box'], decor:['Cedar scent diffuser','Cream table lamp','Paper-shade floor lamp','Linear wall light','Curved wall light','Minimal candle holder','Abstract wood sculpture','Leafy faux floral','Woven lampshade','Warm string light'], kitchen:['Plant-fiber placemat','Washed cotton tablecloth','Cork trivet','Slim kitchen rack','Oak serving tray','Rotating spice rack','Pot-lid organizer','Bamboo cutlery box','Stackable food container','Sink caddy basket'] }
const priceTiers = { furniture:[289,399,259,329,119,249,269,229,189,149], soft:[79,109,39,49,59,89,69,59,99,35], daily:[119,49,29,89,39,45,35,69,39,29], decor:[29,89,159,79,45,39,69,35,59,25], kitchen:[19,39,15,49,35,29,39,29,25,29] }
const products = categoryInfo.flatMap(cat => names[cat.key].map((name, i) => ({ id:`${cat.key}-${i+1}`, name, category:cat.name, key:cat.key, price:priceTiers[cat.key][i], image:`/products/${cat.key}-${i+1}.webp`, tag:i===0?'New':'Featured', desc:`A considered ${name.toLowerCase()} made with natural materials and quiet lines for everyday living.` })))

function App(){
  const [page,setPage]=useState('home'); const [activeCat,setActiveCat]=useState('All'); const [cart,setCart]=useState([]); const [cartOpen,setCartOpen]=useState(false); const [menuOpen,setMenuOpen]=useState(false); const [search,setSearch]=useState('');
  const filtered=useMemo(()=>products.filter(p=>(activeCat==='All'||p.category===activeCat)&&(!search||p.name.toLowerCase().includes(search.toLowerCase()))),[activeCat,search]);
  const add=(product, buy=false)=>{setCart(c=>{const found=c.find(x=>x.id===product.id);return found?c.map(x=>x.id===product.id?{...x,qty:x.qty+1}:x):[...c,{...product,qty:1}]});setCartOpen(!buy);if(buy)setPage('checkout')};
  const change=(id,delta)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:x.qty+delta}:x).filter(x=>x.qty>0));
  const total=cart.reduce((s,x)=>s+x.price*x.qty,0);
  const go=(p,cat='All')=>{setPage(p);setActiveCat(cat);setMenuOpen(false);window.scrollTo({top:0,behavior:'smooth'})}
  if(page==='checkout') return <Checkout cart={cart} total={total} go={go} />
  if(page==='admin') return <Admin go={go}/>
  if(page!=='home'&&page!=='shop') return <InfoPage type={page} go={go}/>
  return <><Header go={go} cartCount={cart.reduce((s,x)=>s+x.qty,0)} cartOpen={()=>setCartOpen(true)} search={search} setSearch={setSearch} menuOpen={menuOpen} setMenuOpen={setMenuOpen}/><main>
    {page==='home'&&<Hero go={go}/>}<section className="catalog" id="catalog"><div className="section-top"><div><p className="eyebrow">{page==='home'?'CURATED FOR SLOW DAYS':'THE FULL COLLECTION'}</p><h2>{page==='home'?'Make room for living.':'All pieces'}</h2></div><div className="filter-row"><button className={activeCat==='All'?'active':''} onClick={()=>setActiveCat('All')}>All</button>{categoryInfo.map(c=><button key={c.name} className={activeCat===c.name?'active':''} onClick={()=>setActiveCat(c.name)}>{c.name}</button>)}</div></div><div className="product-grid">{filtered.map(p=><ProductCard key={p.id} product={p} add={add}/>)}</div></section>
    {page==='home'&&<Story go={go}/>}<TrustStrip/>
  </main><Footer go={go}/><CartDrawer open={cartOpen} setOpen={setCartOpen} cart={cart} change={change} total={total} go={go}/></>
}
function Header({go,cartCount,cartOpen,search,setSearch,menuOpen,setMenuOpen}){return <header><div className="utility">Free delivery over $120 · Designed for everyday living <span>HK / USD</span></div><nav className="nav"><button className="icon-btn mobile-menu" onClick={()=>setMenuOpen(!menuOpen)}><Menu size={20}/></button><button className="brand" onClick={()=>go('home')}>SMILER<span>/</span>LIFE</button><div className={`nav-links ${menuOpen?'show':''}`}><button onClick={()=>go('home')}>Home</button><button onClick={()=>go('shop')}>Shop all</button><button onClick={()=>go('about')}>Our story</button><button onClick={()=>go('shipping')}>Delivery</button></div><div className="nav-tools"><div className="search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search pieces"/></div><button className="cart-link" onClick={cartOpen}><ShoppingBag size={18}/><span>{cartCount}</span></button></div></nav></header>}
function Hero({go}){return <section className="hero"><div className="hero-copy"><p className="eyebrow">A NEW KIND OF HOME GOODS</p><h1>Small rituals.<br/><em>Better rooms.</em></h1><p>Furniture, textiles and everyday objects designed to make home feel a little more considered.</p><button className="button dark" onClick={()=>go('shop')}>Explore the collection <ArrowRight size={16}/></button></div><div className="hero-image"><img src="/products/furniture-1.webp" alt="Sculptural lounge chair"/><div className="hero-note">01 / 05<br/><b>Objects with a point of view.</b></div></div></section>}
function ProductCard({product,add}){return <article className="product-card"><div className="product-image"><img src={product.image} alt={product.name}/><span>{product.tag}</span><button className="wish"><Heart size={16}/></button></div><div className="product-meta"><div><h3>{product.name}</h3><p>{product.category}</p></div><strong>${product.price}</strong></div><div className="product-actions"><button onClick={()=>add(product)}>Add to Cart</button><button onClick={()=>add(product,true)}>Buy Now · ${product.price}</button></div></article>}
function Story({go}){return <section className="story"><div className="story-image"><img src="/products/soft-4.webp" alt="Natural textiles and linework art"/></div><div className="story-copy"><p className="eyebrow">OUR APPROACH</p><h2>Good design should feel like a deep breath.</h2><p>We believe a home does not need to be filled. Smiler Life starts with quiet colors, durable materials and useful details, leaving every room a little breathing space.</p><button className="text-link" onClick={()=>go('about')}>Our story <ArrowRight size={16}/></button></div></section>}
function TrustStrip(){return <section className="trust"><div><Truck/><span><b>Reliable delivery</b> Free over $120</span></div><div><ShieldCheck/><span><b>Shop with ease</b> 14-day returns</span></div><div><Sparkles/><span><b>Considered materials</b> Made for daily life</span></div><div><PackageCheck/><span><b>Order tracking</b> Every step visible</span></div></section>}
function CartDrawer({open,setOpen,cart,change,total,go}){return <><div className={`shade ${open?'show':''}`} onClick={()=>setOpen(false)}/><aside className={`drawer ${open?'open':''}`}><div className="drawer-head"><h2>Your cart <span>{cart.reduce((s,x)=>s+x.qty,0)}</span></h2><button onClick={()=>setOpen(false)}><X/></button></div>{cart.length===0?<div className="empty"><ShoppingBag size={34}/><p>Your cart is waiting for something lovely.</p></div>:<><div className="drawer-items">{cart.map(x=><div className="drawer-item" key={x.id}><img src={x.image} alt=""/><div><h3>{x.name}</h3><p>${x.price}</p><div className="qty"><button onClick={()=>change(x.id,-1)}><Minus size={12}/></button><span>{x.qty}</span><button onClick={()=>change(x.id,1)}><Plus size={12}/></button></div></div></div>)}</div><div className="drawer-foot"><div><span>Subtotal</span><strong>${total.toFixed(2)}</strong></div><small>Taxes and delivery calculated at checkout.</small><button className="button dark full" onClick={()=>{setOpen(false);go('checkout')}}>Checkout <ArrowRight size={16}/></button></div></>}</aside></>}
function Checkout({cart,total,go}){return <div className="checkout-page"><Header go={go} cartCount={cart.reduce((s,x)=>s+x.qty,0)} cartOpen={()=>{}} search="" setSearch={()=>{}} menuOpen={false} setMenuOpen={()=>{}}/><div className="checkout-wrap"><button className="back-link" onClick={()=>go('shop')}>← Continue shopping</button><div className="checkout-grid"><section><p className="eyebrow">SECURE CHECKOUT DEMO</p><h1>Almost home.</h1><div className="checkout-card"><h3>Contact information</h3><div className="form-grid"><input placeholder="Email address"/><input placeholder="Phone (optional)"/></div><h3>Delivery address</h3><div className="form-grid"><input placeholder="First name"/><input placeholder="Last name"/><input className="wide" placeholder="Address"/><input placeholder="City"/><input placeholder="Postal code"/></div><h3>Payment method</h3><div className="payment-options"><button className="selected"><span className="paypal">PayPal</span><Check size={16}/></button><button><span className="visa">VISA</span><span>•••• 4242</span></button><button><CreditCard size={20}/><span>Credit / debit card</span></button></div><button className="button dark full">Pay ${total.toFixed(2)} <ArrowRight size={16}/></button><p className="demo-note">Payment is a frontend demo. Connect a real PayPal or Stripe merchant account to enable live payments.</p></div></section><aside className="order-summary"><h3>Your order</h3>{cart.map(x=><div className="summary-item" key={x.id}><img src={x.image}/><span>{x.name} × {x.qty}</span><b>${(x.price*x.qty).toFixed(2)}</b></div>)}<div className="summary-total"><span>Total</span><strong>${total.toFixed(2)}</strong></div></aside></div></div></div>}
function InfoPage({type,go}){
  const data={
    about:['About us','Make everyday living feel a little better.','We are the home-living selection store of 笑爾貿易有限公司, focused on durable furniture, textiles, storage and lighting. Every piece balances function, material and an approachable price.'],
    shipping:['Shipping policy','From our warehouse to your door, we look after every step.','Orders are usually processed within 1–3 business days. Furniture and large items arrive in 5–12 business days; daily essentials arrive in 3–8 business days. Standard delivery is free on orders over $120.'],
    returns:['Returns & refunds','If it is not right, we make it easy to change course.','Returns can be requested within 14 days of delivery. Items must be unused, undamaged and in original packaging. Return shipping for a change of mind is the customer’s responsibility; defects and incorrect items are covered by us.'],
    cancel:['Cancellation policy','If it has not left yet, we will try to help.','Orders may be cancelled by email before dispatch. Once an order enters fulfillment, the returns policy applies. Custom, clearance and opened hygiene items cannot be cancelled.'],
    tracking:['Order tracking','Know where it is, all the way home.','Send your order number and purchase email to xiaoerkejishop@outlook.com and we will reply with tracking information within one business day.'],
    privacy:['Privacy policy','We only collect what is needed to complete your order.','We may collect your name, email, phone, delivery address and order details to process orders, deliver goods, provide support and prevent fraud. We do not sell personal data. Payment providers process payment details; we do not store full card numbers.'],
    dmca:['DMCA','We respect original work and respond promptly.','If you believe content on this site infringes your copyright, email us with a description of the work, proof of rights, the relevant URL and your contact details. We will review complete notices and take appropriate action.'],
  }
  const terms=['Definitions and scope','Product information and stock','Prices and currency','Orders and confirmation','Payment methods','Delivery regions and timing','Order tracking','Return eligibility','Refund process','Order cancellation','Product quality and support','Intellectual property','User content','Privacy and data','Limitations of liability','Policy changes','Governing law and contact'];
  const d=data[type]||data.about;
  return <><Header go={go} cartCount={0} cartOpen={()=>{}} search="" setSearch={()=>{}} menuOpen={false} setMenuOpen={()=>{}}/><main className="info-page"><p className="eyebrow">SMILER LIFE / INFORMATION</p><h1>{type==='terms'?'Terms of Service':d[0]}</h1><p className="lead">{type==='terms'?'Clear, readable terms for every purchase.':d[1]}</p><div className="info-content">{type==='terms'?<>{terms.map((title,i)=><section key={title}><h3>{i+1}. {title}</h3><p>This section explains the rights, responsibilities and handling standards for {title.toLowerCase()} between Smiler Life and our customers. Published product pages, order confirmations and support emails form part of the information for your purchase.</p></section>)}</>:<><p>{d[2]}</p><p>For help, contact <a href={`mailto:${company.email}`}>{company.email}</a>. We aim to handle every request clearly and kindly.</p></>}</div></main><Footer go={go}/></>
}
function Footer({go}){return <footer><div className="footer-main"><div><button className="brand footer-brand" onClick={()=>go('home')}>SMILER<span>/</span>LIFE</button><p>Make room for living.<br/>Leave a little space for living.</p><div className="social"><Globe2 size={17}/><AtSign size={17}/></div></div><div><h4>Shop</h4>{categoryInfo.map(c=><button key={c.name} onClick={()=>go('shop',c.name)}>{c.name}</button>)}</div><div><h4>Help</h4><button onClick={()=>go('shipping')}>Shipping policy</button><button onClick={()=>go('returns')}>Returns & refunds</button><button onClick={()=>go('cancel')}>Cancellation policy</button><button onClick={()=>go('tracking')}>Order tracking</button></div><div><h4>Company</h4><button onClick={()=>go('about')}>About us</button><button onClick={()=>go('terms')}>Terms of Service</button><button onClick={()=>go('privacy')}>Privacy policy</button><button onClick={()=>go('dmca')}>DMCA</button><button onClick={()=>go('admin')}>Admin demo</button></div></div><div className="footer-contact"><div><b>{company.name}</b><span>{company.address}</span><span>Phone: not provided · Registration no.: not provided</span></div><a href={`mailto:${company.email}`}>{company.email}</a></div><div className="footer-bottom"><span>© 2026 {company.name}. All rights reserved.</span><span>Pay securely with <b className="paypal">PayPal</b> <b className="visa">VISA</b> <CreditCard size={16}/></span></div></footer>}
function Admin({go}){const [logged,setLogged]=useState(false);return <div className="admin-page"><div className="admin-card"><button className="brand" onClick={()=>go('home')}>SMILER<span>/</span>LIFE</button>{logged?<><p className="eyebrow">DEMO ADMIN</p><h1>Welcome back.</h1><p>Product, order and content management is ready. This is a frontend demo and is not connected to a live database or payment service.</p><button className="button dark full" onClick={()=>go('home')}>Back to storefront</button></>:<><p className="eyebrow">STORE ADMIN / DEMO ACCESS</p><h1>Admin sign in</h1><p className="admin-muted">This login is for local frontend demonstration only.</p><input defaultValue="admin@smilerlife.com" aria-label="email"/><input type="password" defaultValue="SmilerLife2026!" aria-label="password"/><button className="button dark full" onClick={()=>setLogged(true)}>Sign in <ArrowRight size={16}/></button><p className="credentials">Demo email: admin@smilerlife.com<br/>Demo password: SmilerLife2026!</p></>}</div></div>}
export default App

createRoot(document.getElementById('root')).render(<App />)
